driver:
  name: vagrant
  synced_folders:
    - ["C:/Installers", "c:/Installers"]

provisioner:
  name: chef_zero
  # You may wish to disable always updating cookbooks in CI or other testing environments.
  # For example:
  #   always_update_cookbooks: <%= !ENV['CI'] %>
  always_update_cookbooks: true
  require_chef_omnibus: true

verifier:
  name: inspec
  format: junit
  output: '%{platform}_%{suite}_inspec.xml'

transport:
  name: winrm

platforms:
  - name: win10
    os_type: windows
    shell_type: powershell

suites:
  - name: default
    run_list:
      - recipe[oracle-xe-windows::default]
    verifier:
      inspec_tests:
        - test/smoke/default
    attributes:
        oracle-xe-windows:
          url: c:/Installers/OracleXE112_Win64/DISK1/setup.exe
